### ISSUE TITLE
it's annoying to type -- to pass arguments through to invoked process

### ISSUE THREAD

**Issue by Gobiner** [Oblong/obi#100]
I'm tired of typing `obi go -- --show-fipser`, that's a whole three keystrokes wasted.

Why shouldn't obi automatically pass unrecognized flags through to the process it invokes? If I type `obi go --show-fipser` can't obi infer that I want to pass that flag through because obi doesn't have a fipser to show?

**Comment by tomjakubowski** [comment]
Extra args should be explicitly separated because otherwise we can never
add new flags to obi without risk of breaking users.
