### ISSUE TITLE
"curl: (35) Server aborted the SSL handshake" on "brew install obi"

### ISSUE THREAD

**Issue by nohle** [Oblong/obi#102]
On `brew install obi`, I get the error "curl: (35) Server aborted the SSL handshake"

The command `brew install obi --HEAD` works just fine though.

**Comment by sandover** [comment]
Thanks for the report!

**Comment by jshrake** [comment]
Likely related to https://status.aws.amazon.com/

**Comment by Gobiner** [comment]
Safe to close?
