### ISSUE TITLE
Bash completion: roomname completion is fragile for multi-python users with Homebrew install

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#108]
The `_obi_roomnames` function assumes that:

* python is on the user's PATH (which is not actually a requirement for Homebrew obi)
* the python on the user's PATH is the same python used for obi (which I think is hardcoded to `/usr/bin/python`
* that the yaml package is findable on PYTHONPATH in the shell's context

None of these assumptions need be true for obi to run on Homebrew, because we "vendor" all dependencies (including yaml) and inject them into PYTHONPATH when running obi: https://github.com/Oblong/homebrew-tools/blob/master/obi.rb#L52-L64

For example, I removed `pyyaml` from my system with pip and room completion fails thusly:

```
bash-3.2$ pip uninstall pyyaml
Uninstalling PyYAML-3.12:
...
bash-3.2$ obi go <TAB>Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ImportError: No module named yaml
--
```

**Comment by tomjakubowski** [comment]
In fact, I bet that if you took a brand new Mac laptop, installed Homebrew on it, tapped Oblong/homebrew-tools, and installed obi, without making any other changes, you'd see the same roomname completion problem.

**Comment by Gobiner** [comment]
This is fixed now (on the dev branch).
