### ISSUE TITLE
change yovo template to gspeak

### ISSUE THREAD

**Issue by mattieruth** [Oblong/obi#12]
the name yovo is only internal.  It is more accurate to have a gspeak template.

**Comment by tomjakubowski** [comment]
The new obi doesn't ship with any templates, so right now that template is internal-only. We could still rename it of course. Check out the obi/yovo repo on GitLab.

**Comment by tomjakubowski** [comment]
Oh, we also refer to these templates (among other internal ones) by name in this project's README.md

**Comment by jshrake** [comment]
Handling this in our internal repo
