### ISSUE TITLE
rsync-extra-opts: [] seem to leak into the rsync command line

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#127]
`obi build room` from a fresh `obi new gspeak` was failing here:

```
Fatal error: local() encountered an error (return code 23) while executing 'rsync --delete --exclude ".git" --exclude "build" -pthrvz [] --rsh='ssh  -p 22 ' /Users/tjakubowski/tmp/fail/ oblong@xxxxx:/tmp/tjakubowski/fail'

Aborting.
```

Note that `-pthrvz []`. I had this in my project.yaml:

```yaml
rsync-extra-opts: []
```

When I commented out that line in project.yaml, the rsync command line looked like this:

```
rsync --delete --exclude ".git" --exclude "build" -pthrvz --copy-links --partial --rsh='ssh  -p 22 ' /Users/tjakubowski/tmp/fail/ oblong@xxxxx:/tmp/tjakubowski/fail
```

And succeeded.

This was running off commit 7aa4a48e3ecd04c3311f72b150cff3a770c1af11 from master.

**Comment by Gobiner** [comment]
I've fixed all the templates that had this. Turns out `rsync-extra-opts` is a string and not a list!

**Comment by tomjakubowski** [comment]
>  I've fixed all the templates that had this. Turns out rsync-extra-opts is a string and not a list!

ugh
