### ISSUE TITLE
consider generalizing or removing `pools` feature

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#13]
So when you define a room in `project.yaml`, you can specify pools:

```
  ncc-1701-bridge:
    # yeah, they still use IPv4 in the 23rd century
    pools: {wands-pool: 'tcp://192.168.1.100/wands'} 
```

These get passed as command line arguments to the process.  This is a wee-bit Oblong specific.

**Comment by jshrake** [comment]
I went a bit further and removed all Oblong specific keys:
- feld-protein
- screen-protein
- room-protein
- pools

There is no backwards-compatibility support. Don't jump to upgrade yet.
