### ISSUE TITLE
obi rsync wants to sync previously fetched items

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#138]
Maybe this is a bug in the templates, but:

When I run `obi fetch <room> some_file.txt`, it creates a directory named `fetched.TIMESTAMP` in my working directory (or maybe in the project directory?), and puts copies of those files in those directories.

The next time I run `obi build <room>` or `obi go <room>`, those files get schlepped back up to every machine in those `fetched` dirs. I would venture to say this is never something a typical user would want to happen.

**Comment by Gobiner** [comment]
Adding `fetched.*` to the list of rsync excludes in project.yaml fixes this for me. My inclination is to add it to our templates and leave obi's code unchanged.

**Comment by Gobiner** [comment]
I added `fetched.*` to all our templates.
