### ISSUE TITLE
obi template upgrade --all does not signal success/failure that well

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#139]
I have five templates:

```
% obi template list
Installed templates:
cpp
greenhouse
growroom
gspeak
seabed
```

("Installed templates:" is not one of them)

Here's what a successful upgrade looks like:

```
% obi template upgrade --all
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/cpp:
Already up-to-date.
Current branch master is up to date.
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/greenhouse:
Already up-to-date.
Current branch master is up to date.
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/growroom:
Already up-to-date.
Current branch master is up to date.
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/gspeak:
Already up-to-date.
Current branch master is up to date.
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/seabed:
Already up-to-date.
Current branch master is up to date.
% echo $?
0
```

So when all goes well, I get three lines of output for every template I have, and obi exits with code 0.

Here's what it looks like when I have, say, a dirty working tree in one of those templates (maybe because I was experimenting a while ago and forgot to make a commit + push to a branch, or something):

```
% obi template upgrade --all
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/cpp:
Already up-to-date.
Current branch master is up to date.
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/greenhouse:
Already up-to-date.
Current branch master is up to date.
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/growroom:
Already up-to-date.
Current branch master is up to date.
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/gspeak:
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
Upgrading template at /Users/tjakubowski/.local/share/oblong/obi/seabed:
Already up-to-date.
Current branch master is up to date.
% echo $?
0
```

When something goes sideways, I get (in this particular case) three lines of output for the template that failed to upgrade, and three lines of output per template whose upgrade succeeded. I see an exit code of 0.

* * *

What I'm getting at here is that failure and success cases are hard to distinguish, both programmatically (checking the exit code) and with the eye, especially if you run `obi template upgrade --all` as a sort of "background task" while focused on other things. If obi printed a bunch of spam only when an error happened (signaled, probably, by the `git` command returning a non-0 exit code!), it would be easier to spot errors when they occur.

**Comment by tomjakubowski** [comment]
Oh, and obi should definitely not exit with code 0 when a template upgrade fails.

**Comment by Gobiner** [comment]
This issue was fixed in https://github.com/Oblong/obi/commit/aa198b098548bcb5d2f0589d3ad937586d105e6b
