### ISSUE TITLE
obi-generated files are missing trailing newlines

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#14]
Even if the template file in a project template has a trailing newline, the file generated by Obi lacks it.  This causes diff churn and real problems in git (in particular, our buildbot assumes trailing newline in all files for try builds in order for the patching to succeed).

To reproduce, I installed the gspeak-headless template, and then ran `obi new gspeak-headless foo`.  If I catted `src/main.cpp` in the generated project, it was missing a trailing newline, looking like this in my terminal:

![screen shot 2015-10-19 at 5 05 46 pm](https://cloud.githubusercontent.com/assets/667901/10594612/a909a738-7683-11e5-9d00-e8edd13c16bb.png)

**Comment by tomjakubowski** [comment]
jinja2 has an option `keep_trailing_newline`, see http://jinja.pocoo.org/docs/dev/api/

**Comment by tomjakubowski** [comment]
also, lol: https://gcc.gnu.org/ml/gcc/2003-11/msg01568.html

**Comment by tomjakubowski** [comment]
This might need to be fixed in every template, unless obi can set that value in some global way that all jinja2 environments inherit.

**Comment by jshrake** [comment]
Solving this at the template level for now.
