### ISSUE TITLE
obi clean should also clean the bin/ directory

### ISSUE THREAD

**Issue by sandover** [Oblong/obi#20]
(or the bin/ directory should not exist)

**Comment by tomjakubowski** [comment]
cmake offers a `make clean`, I believe, so a `pre-clean-cmd` which calls that would work (if `pre-clean-cmd` is a thing)

**Comment by tomjakubowski** [comment]
Turns out the `make clean` target that CMake generates doesn't clear anything out from the `bin/` directory. Rats.

**Comment by jshrake** [comment]
Let's stop moving our build artifacts outside of the build directory. This change impacts the obi templates and requires no code change in obi. Closing.
