### ISSUE TITLE
"obi ls" should probably be called "obi template list"

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#21]
for consistency's sake.

**Comment by tomjakubowski** [comment]
(this also frees up `obi ls` to do something interesting in the future)

**Comment by tomjakubowski** [comment]
More thoughts on this:

I would like a convenient shell one-liner to update all of my templates. More generally, I would like to be able to write convenient shell-oneliners to do (some action) on all of my templates.

Today, `obi ls 2>/dev/null` outputs this to stdout:

```
Installed templates:
cpp
greenhouse
gspeak
seabed
```

If not for that first line, I could do something like (assuming no spaces in my template names… though there are workarounds for that)

```
for temp in $(obi ls); do obi template upgrade $temp; done
```

But because of that "Installed templates" header line, I have to add a tail to the subshell pipeline. Oh, the humanity!

```
for temp in $(obi ls | tail -n +2); do obi template upgrade $temp; done
```

But I think it's reasonable to include that line of output. It's probable someone might run `obi ls` after seeing it in the help screen without knowing what it does. The extra line of output is helpful in describing what comes next.

If the command were called `obi template list`, I think it would be totally fair to remove the "Installed templates" line from the output.  And then my one-liner would be cleaner. :-)

**Comment by tomjakubowski** [comment]
I'm going to submit an unsolicited MR about this, even though I'm the only person who seems to care. More evidence `obi ls` is the wrong name: to list templates, you use `obi ls`, but to remove a template you don't use `obi template rm`, you use `obi template remove`.

**Comment by dankegel** [comment]
Blind user experience note: I was surprised there was no obi template ls recently, and didn't see the obi ls command.  

I prefer short names, so
  obi t ls
should work.  And I don't mind if the heading line is dropped or requires a -f --fancy option.

**Comment by sandover** [comment]
Commands should be consistent.  All commands directly touching on templates should use the `obi template` format.  

If we want to go to a different format, we could entertain that in a separate ticket.
If we want to support shortened forms, I think that would also be a new ticket.

**Comment by sandover** [comment]
Having said that, why not stick with the standard unix commands?

- `obi template ls`
- `obi template rm`

**Comment by dankegel** [comment]
yes, please.  ls and rm are nice, short, and familiar.

**Comment by Gobiner** [comment]
I created a new issue for nice short names. https://github.com/Oblong/obi/issues/72
