### ISSUE TITLE
Pass additional arguments to cmake in "obi build"

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#22]
I'd like to be able to pass additional cmake arguments to `obi build`, the same way I can pass additional runtime arguments to my program with `obi go`:

```
$ obi build -- -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```

the motivating reason being that I'm trying out [rtags](https://github.com/Andersbakken/rtags), which uses CMake's "compilation commands database" feature, but I don't want to necessarily force this CMake flag on other developers.  I could see this having other niche uses as well.

**Comment by tomjakubowski** [comment]
I've since worked around this by writing a shell script wrapper around cmake and sticking it early in my PATH.

But, upon reflection, I can see this proposed being confusing. The extra arguments would be passed to cmake, but `obi build` has two responsibilities: running cmake ("configure") and then actually building the thing. Maybe you'd like to pass arguments to whatever actually builds your thing (Ninja, Make, tup, whatever), too, but there wouldn't be a way to add that feature with this one in place.

**Comment by Gobiner** [comment]
on reflection: wontfix
