### ISSUE TITLE
Overriding build-cmd with "" results in default build command running

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#24]
Since Python treats empty strings as falsy, `build_task` will use the default build command (using CMake) if the user provides `build-cmd: ""`.   See https://github.com/Oblong/obi/blob/a7452af911c5daee643b25b22f71f58b736e163f/obi/task/task.py#L139

My expectation is that providing an empty build-cmd, or `build-cmd: ~` would make the build-task a no-op.  Instead, I have to provide something like `build-cmd: /usr/bin/env true`

**Comment by jshrake** [comment]
Should be fixed by #78, thanks @Gobiner!
