### ISSUE TITLE
"obi test"

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#27]
Let's say I've written an application with a test suite.  I'd like to be able to build and run the test suite as easily as I can run the main target, in any of the rooms configured in my project.yaml.

I could duplicate one of my rooms and override the target, and run something like `obi go secret-volcano-base-test`.  But that's a lot of work and duplication to keep track of. What's worse, if I run the tests in a remote room, I have to ssh to the and check the test results on each machine, because obi redirects remote runs to a log file.

`obi test secret-volcano-base` (with a `test-cmd` key in the project.yaml), which echoes stdout/stderr from each remote process back to the user, seems nicer to me.

**Comment by tomjakubowski** [comment]
Do we want separate `test-build-cmd` and `test-run-cmd` settings?

**Comment by tomjakubowski** [comment]
> Do we want separate test-build-cmd and test-run-cmd settings?

No, we should just assume that `obi build` produces the test runners too.

**Comment by Gobiner** [comment]
I would also like to have an `obi test` command.

**Comment by sandover** [comment]
Could be part of a broader refactor where it becomes easier to add arbitrary commands to obi.  As currently set up, that would be hard to do.

**Comment by jshrake** [comment]
Closing. We can accomplish this now by adding a room with a target and/or set of command-line args that runs a test binary or cmake test.
