### ISSUE TITLE
Allow opt-out of backgrounding remote processes

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#28]
If you run `obi go secret-volcano-base`, the "launch task" process's stdout and stderr seemingly disappear into the ether, and the process runs in the background. This is a good default, but sometimes I'd like to be able to see stdout/stderr in real-ish time without sshing to the remote hosts and tailing a logfile, and to be able to kill the remote process by mashing Ctrl+C.

Ideally, `obi go --foreground secret-volcano-base` or `obi go -f secret-volcano-base` would do the trick. There could be a project/room setting for this, too. (in that case, you'd also want `--background`/`-b` flags)

**Comment by jshrake** [comment]
Good feature request for a future refactor.
