### ISSUE TITLE
Migrate room config outside of project.yaml

### ISSUE THREAD

**Issue by EchoAbstract** [Oblong/obi#29]
Storing the room configurations in `project.yaml` has several disadvantages:
1. The `project.yaml` contained in the templates is mostly useful for people in Oblong's LA office.
2. The number of room configs in `project.yaml` grows very large as we collaborate on projects in multiple locations and support more deployed rooms.
3. If a room configuration changes each project that knows about the room needs to be updated with the new configuration (think if a system's IP address or hostname changes). 

A possible idea would be having rooms or roomsets as separate configuration files that are controlled in a git repo and having obi wrap pull them down like templates.  Something like:

```
room install  Install an obi room
room remove   Remove an installed obi room
room upgrade  Upgrade an installed obi room

# Used like
obi room install boston-wall
obi go boston-wall

obi room install warehouse
obi go wall
```

The only thing that's missing is some way to "package" or lock a room configuration for deployment.

**Comment by tomjakubowski** [comment]
This is great and :+1: to it overall, but the feature to control command line arguments and environment variables for a project on a per-room basis is crucial.  So the project.yaml file still needs to have some "knowledge" of rooms, but it doesn't need to "know" the specific details of a room's hosts (like their IPs, usernames, etc.)

**Comment by tomjakubowski** [comment]
On the other hand, the ability to ship a project's source to a client and let them run on a remote host without needing anything installed but obi is very nice.  The room install step is somewhat onerous.

**Comment by EchoAbstract** [comment]
>  The room install step is somewhat onerous.

Yeah, that's why we need someway to package the room configs with the project.  We wouldn't want to have to do an `obi room` command when installing at a customer site either.

**Comment by tomjakubowski** [comment]
I guess we could have obi check some magic directory in the project (like "rooms") for room configuration files.  Then we could have a git repo for Acme Corp rooms, and pull that in as a submodule to all the Acme Corp projects.

**Comment by sandover** [comment]
Hmm, I guess I still don't accept the initial problem statement as something that would motivate a big design change.  Real world project.yamls I have seen include 5-15 room settings; if this number were 50, I still don't see a `grows very large` problem yet.  For comparison, a not unreasonable .ssh/config might contain 50 or 100 entries.

**Comment by tomjakubowski** [comment]
@jshrake made a good point that the problem is "how to run" and "where to run" are intertwined in one place now, the project.yaml file.  If we specify "where to run" globally (somewhere in a user's ~, or maybe even in places like /usr/local/etc), you still need to specify per-project how to run the thing in each location.

We also have some room parameters that most projects running in a given location end up using: things like a `DISPLAY=':0'`environment variable, or build arguments like `-j32 -l32`, or command line arguments like paths to room/screen/feld proteins and the wands pool configuration.

**Comment by jshrake** [comment]
Good feature for a future refactor.
