### ISSUE TITLE
`obi go -f` or `obi go --foreground` flag for local rooms

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#3]
It seems that the switch to backgrounding/`nohup`ing processes and redirecting their output for local rooms is breaking users' expectations.  While I like that we can more easily match the behavior of remote rooms this way, I do agree that it's a bit annoying to have to tail that log file for output while developing (it greatly hinders "printf debugging").

Programs which dæmonize (and log to a file/syslog) by default often include a flag like `--foreground` or `-f` for running in the foreground and logging to stdout.  It may even be desirable for remote runs, if that can work with fabric (I don't see why it wouldn't).

**Comment by jshrake** [comment]
Resolved via https://github.com/Oblong/obi/commit/c8e6615641d6897b40b3f5d54cf6b56ff036144d

The expected behavior now matches obi1.0. Output is directed to stdout and a log file via `tee`.
