### ISSUE TITLE
Look at obi Xcode integration

### ISSUE THREAD

**Issue by EchoAbstract** [Oblong/obi#30]
Science project to enable something like: `obi xcode` to have obi create an Xcode build directory and install the settings from `project.yaml` in the Xcode schemes and (maybe) launch Xcode.

**Comment by tomjakubowski** [comment]
Can't you just pass the right arguments to CMake to have it produce these things (see #22)? Why does it need a dedicated command?

**Comment by EchoAbstract** [comment]
AFAIK there is no way to configure the scheme in Xcode based on the contents of `project.yaml` using CMake.  These are things like the command line arguments, etc.

**Comment by tomjakubowski** [comment]
Aha. Maybe, then, an `obi go --dry-run` would be useful (see https://github.com/Oblong/obi/issues/23#issuecomment-171102322)? 


```bash
obi go --skip-prereqs --dry-run | pbcopy
# paste into Xcode
```

You'd need to update the  command line arguments in Xcode whenever they change in the project.yaml.

**Comment by EchoAbstract** [comment]
Which is where I figured the command would come in handy :-)

**Comment by dankegel** [comment]
see also https://cmake.org/Bug/view.php?id=15441

**Comment by EchoAbstract** [comment]
I don't think we need to do this one.
