### ISSUE TITLE
Document the project.yaml format

### ISSUE THREAD

**Issue by jshrake** [Oblong/obi#31]
The closest documentation for the `project.yaml` format is buried away in https://github.com/Oblong/obi/wiki/Upgrading-from-obi-1.0-to-3.0

**Comment by sandover** [comment]
Would including in the man page make sense?  Would that be enough?

**Comment by sandover** [comment]
One gotcha: when specifying launch-cmd, you FULLY specify launch command -- other project.yaml inputs stop being used by obi at that point.  This came as a surprise to me.

**Comment by Gobiner** [comment]
I have updated the project.yamls in our templates to show all available options, and to document their functionality. Additionally, I've copied one such project.yaml into the obi repo itself https://github.com/Oblong/obi/commit/c4cf1ff4a83cd4276074b72878129d495a0210bc
