### ISSUE TITLE
pkill command's pattern is too broad

### ISSUE THREAD

**Issue by EchoAbstract** [Oblong/obi#32]
The pattern fed to `pkill` in `obi-go-localhost.sh` matches too much.

I named an app `d`, ran `obi go` and was booted back to the login screen.  `obi-go-localhost.sh` runs `pkill -KILL -f '[a-z/]+d .*' || true` prior to running the app.

``` sh
$ ps -u bwilson -o args | egrep '[a-z/]+d .*'
//bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
<many chrome processes>
```

So the pkill command kills dbus and I get booted to login screen on linux.

The pattern currently matches any app whose name ends with your app name, or which was run with a  command line argument that ends in your app's name _and_ there are more arguments on the command line. 

Other fun project names are `dio`:

``` sh
$ ps -u bwilson -o args | egrep '[a-z/]+dio .*'
/usr/bin/pulseaudio --start --log-target=syslog
```

`pkill` will happily restart `pulseaudio`

and `long`:

``` sh
$ hostname
boston-wall-right
$ ps -eo args | egrep '[a-z/]+long .*'
su oblong -c /usr/bin/startx
sshd: oblong [priv] 
```

`pkill` will likely kill Xorg (and `sshd`)

**Comment by tomjakubowski** [comment]
Ouch. I'm trying to remember firstly why we use a regex that matches absolute paths, and secondly why we use pkill -f (maybe to be sure processes running in, say, a debugger get killed).

**Comment by tomjakubowski** [comment]
Oh, ha ha, I dug up some old issues from the old repo and I think I remember why we use the wacky regex, at least.

Now I remember why… from old obi repo issue 26:

> pkill -f macroscope ends up killing the shell that Fabric invokes, because its command line is something like:
> ```
> /bin/sh -c 'pkill -f macroscope || true' 
> #                    ^^^^^^^^^^ note
> ```
> When that shell doesn't exit cleanly, Fabric complains and throws an exception or something.

:confounded: So I guess the question is: do we really *need* to use `-f` here?

> and there are more arguments on the command line.

We should remove this requirement from whatever regex we end up with, too (it only happens to work for targets with empty launch-args because obi adds the `2>&1 | tee -a foo.log` to the end of every launch command).

**Comment by EchoAbstract** [comment]
1 vote for getting rid of `-f`.

**Comment by sandover** [comment]
It would be great to kill precisely the thing that was run by fabric.  Does fabric happen to have support for that notion?  Could it return a pid?

**Comment by tomjakubowski** [comment]
@sandover I'm not sure that's sufficient; I think we broadly consider the ability to kill a colleague's runs of the same project on remote machines with `obi stop` (or `obi go`) to be a feature.

@jshrake has also balked in the past at the idea of persisting state in the form of a "pid file" or similar in the past, with reasonable justification.

**Comment by jshrake** [comment]
The `-f` flag is necessary to handle the case where we need to kill the wrapper process launched by `obi go --debug`. In this case, the process to kill is `gdb`, `lldb`, `strace`, etc. rather than the name of the project. Perhaps `obi stop` has outgrown a simple `pkill` one-liner.

**Comment by tomjakubowski** [comment]
@jshrake maybe it's just a matter of making the regex more specific, using the knowledge obi has of the project and the way it runs things. For example, since obi go always seems to run something like `sh -c '(( nohup /tmp/tjakubowski/hello/bin/hello ))` on remote hosts, it could do this for `obi stop moonbase`:

```bash
pkill -KILL -f '/tmp/[^/]/PROJECT_NAME/RELATIVE_PATH_TO_TARGET'
```

that should be a strict improvement over the current situation (although still not perfect).

maybe locally it should use an absolute path to start the target too, so it could use that same regex.

**Comment by tomjakubowski** [comment]
`pidof` seems to print only the "real" macroscope's pid (whether this behavior is something we should rely on is another question. I know nothing!):

```
% pgrep -a macroscope
8096 /bin/sh bin/macroscope --config=share/macroscope/config.protein --site=share/macroscope/site-local-wall.protein --remote-debugging-port=9223 --enable-logging=stderr --v=2 three-screen.protein three-feld.protein
8109 /home/tjakubowski/obsrc/astor/macroscope/bin/macroscope.dir/macroscope --config=share/macroscope/config.protein --site=share/macroscope/site-local-wall.protein --remote-debugging-port=9223 --enable-logging=stderr --v=2 three-screen.protein three-feld.protein

% pidof macroscope
8109
```

pidof's man page suggests that you need to pass `-x` to get the shell script wrapper's PID in the output:

```
       -x     Scripts  too  -  this  causes the program to also return process
              id's of shells running the named scripts.
```

**Comment by tomjakubowski** [comment]
so maybe `kill $(pidof macroscope)` is good enough?

**Comment by EchoAbstract** [comment]
Is `pidof` linux only?

**Comment by tomjakubowski** [comment]
Yeah, it's GNU+Linux only (it's not even on Android by default!). There's a homebrew package for it on OS X.

**Comment by EchoAbstract** [comment]
It'd be easy to make obi depend on the pidof package, so it seems like a legit way to get the info we need .

**Comment by tomjakubowski** [comment]
> On Feb 22, 2016, at 16:21, Brian Wilson <notifications@github.com> wrote:
> 
> It'd be easy to make obi depend on the pidof package, so it seems like a legit way to get the info we need .
> 
That's good enough for the local development case, but we should make it known that remote hosts will need pidof. Obi has some users that run on remote OS X hosts.

**Comment by tomjakubowski** [comment]
Related issue (maybe I should file that separately): if your binary name contains a regex special character like `+` or `?`, pkill will do something other than expected.
