### ISSUE TITLE
bad things happen if project name != directory name

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#33]
as discussed with @jshrake: `obi rsync` will put things in a directory based on the local directory name, but `obi build` and `obi go` will operate in a directory based on the project name.

**Comment by tomjakubowski** [comment]
Bit me again today.  I'm working on a project ("foo") from a couple branches at once, and would like to be able to `obi go hex` without flipping between branches in my git working directory over and over.

To do this, I used `git worktree add master master` to checkout the master branch to a folder "master".  But when I `obi go hex` from this directory, everything gets rsynced to `/tmp/tjakubowski/master`, ebut the build/go steps happen in `/tmp/tjakubowski/foo`.

**Comment by jshrake** [comment]
This is fix and tested on dev. Will close when I merge to master.
