### ISSUE TITLE
consider abandoning use of undocumented cmake options

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#35]
https://github.com/Oblong/obi/blob/3545067cd5debc9fb1899661a1396bf46c4cf2ec/obi/task/task.py#L150

The `-H` and `-B` options seem to be totally undocumented (at least in cmake 3.4.3).  It seems potentially dangerous to rely on these options preserving their current behavior, or even existing, in the future.

**Comment by sandover** [comment]
The cmake project is truly scary sometimes.

**Comment by dankegel** [comment]
The man page says -H is for help (synonym for --help).  What are you using it for?
It probably would be a good idea to use the longer option names, they're more self-documenting.

**Comment by tomjakubowski** [comment]
-H is also another way to set the source directory for the project. See http://stackoverflow.com/a/31092052

I have no idea why obi does this rather than passing the source directory as a positional argument.

**Comment by jshrake** [comment]
I stumbled upon the `-H -B` options in a random Hacker News comment and I've used it ever since. The closest thing to "documentation" I can find is http://stackoverflow.com/a/13713684/425495, which also shares your concern that Kitware may squash these options at anytime.

**Comment by sandover** [comment]
@jshrake OK with you if we 

> pass the source directory as a positional argument

?

**Comment by sandover** [comment]
If there' another way to achieve the same goals, that would be nice.

**Comment by jshrake** [comment]
If ever in the future it stops working, let's reopen and fix.
