### ISSUE TITLE
"obi build <remote-room>" don't operate in the current working directory

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#44]
When you run `obi build` locally, the build commands run in the current working directory. When you run `obi build <remote-room>`, the build commands run in the remote user's home directory.  IMO, these should both be changed; commands in both cases should run with the project directory as their CWD.

**Comment by sandover** [comment]
Is this still the case?  Seems surprising.

**Comment by jshrake** [comment]
Resolved by https://github.com/Oblong/obi/commit/7c1bba5ad37f004b1d4266fb0b22f8137300e64d. We can close once we merge dev to master.
