### ISSUE TITLE
Debuggers could be a little more flexible with respect to command arguments

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#45]
Many debugging aids work just fine by simply slapping the whole run command to the end of the line in "debuggers", like `gdb -ex run --args build/my_app --my-cool-arg=so-cool`. But other tools like dtrace and stap want the command in a particular place in the command line invocation.  Could we instead make those strings be "templates", like (pseudo-jinja syntax):

```
debuggers:
  gdb: "gdb -ex run --args {argv|join(' ')}"
```

This might be hard to get right, because dtrace wants the whole command within quotes (like `dtrace -s /path/to/script -c 'build/my_app --my-cool-arg=so-cool'`), so it would need something that can escape characters correctly in context.

**Comment by tomjakubowski** [comment]
On the other hand, we can always just ship a script with our projects that expects command line arguments the way obi hands them over and lightly wraps the debugging tool.

**Comment by sandover** [comment]
Would you mind if we closed this one?
