### ISSUE TITLE
obi build should build from the project directory in remote rooms

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#46]
obi builds on remote machines using an absolute path, from the ~ of the ssh user:

```
[10.137.124.206] run: cmake --build "/tmp/tjakubowski/secret/build" -- -j32 -l32
```

That means if you run `obi build <remote-room>` in Emacs or vim you get absolute paths back from compile errors:

```
[10.137.124.207] out: /tmp/tjakubowski/seaxx/src/main.cpp:3:1: error: ‘wrofgijrogiergore’ does not name a type
```

Unfortunately, this means that you can't click or otherwise select those paths to jump to the error in Emacs or vim. I believe that if obi cd'ed to the project directory and ran `cmake --build build/` instead, the paths would be relative and Just Work(tm) from the developer's machine.

**Comment by jshrake** [comment]
Resolved by https://github.com/Oblong/obi/commit/7c1bba5ad37f004b1d4266fb0b22f8137300e64d. We can close once we merge dev to master.
