### ISSUE TITLE
feature request: re-scaffold just one file from a template

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#50]
common workflow when hacking on an obi template:
1. Make some changes to, say, `main.cpp` in the template.
2. `cd ~/tmp`
3. `obi new mytemplate myproject`
4. wait a while for a submodule checkout or something
5. `cd myproject && obi build`
6. notice that the project doesn't build for some reason
7. `cd .. && rm -rf myproject`
8. Goto 1

Steps four and five there are often a pain and take a long time to complete. It would be nice if I could "rescaffold" just a single file from a template, like:

``` bash
obi renew seabed myproject/main.cpp
```

to avoid rescaffolding and rebuilding the entire project just to test a small fix to a template. Maybe `renew` could take multiple files as arguments to rescaffold.

**Comment by jshrake** [comment]
This is a good feature request for a future refactor. Closing.
