### ISSUE TITLE
If "configure" (Cmake) step fails, obi tries to proceed even with broken build/ directory

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#53]
Steps to reproduce:
1. `obi new cpp bild`
2. `cd bild`
3. Edit the CMakeLists.txt to make it err. For example, forget the closing paren a function call.
4. `obi build`
5. Observe that the `build/`directory was created by cmake, although it's missing some files.
6. Fix the problem in CMakeLists.txt 
7. `obi build`, it will fail again but print something like "Error: could not load cache". (other errors may result, depending on the exact way cmake's configure step failed)

In short, if the cmake configure step fails, it may still produce a directory called `build/`. obi interprets the presence of this directory as the result of a successful `cmake` invocation, so it will skip the "configuration" `cmake` call and just run `cmake --build`. But if the configure step failed, the build step can't succeed.

The workaround is to recognize that cmake's configure (and not build) step failed, and run `obi clean` before running `obi build` again. I think the change that closed #38 is the culprit in this.

**Comment by tomjakubowski** [comment]
If CMake doesn't unambiguously leave some artifact behind indicating that it finished successfully, maybe obi could check cmake's exit status. If cmake is a success, obi would touch a file somewhere in the build directory. If that file doesn't exist when `obi build` runs, then obi would assume cmake failed and try to run it again. Otherwise, `obi build` would skip the cmake step and skip right to the "build" step (something like `cmake --build build/`).

**Comment by jshrake** [comment]
This regression is awful. I reverted 07e290bd4e7e4418156e8f89ba02fb2af48c5fd5 and reopened #38.

**Comment by tomjakubowski** [comment]
grumble, on the other hand after the revert, every time I run `obi build` I'm now faced with spew from re-running cmake even if I didn't touch CMakeLists.txt.
