### ISSUE TITLE
optimize rsync behavior of obi go when more than 2 target machines

### ISSUE THREAD

**Issue by sandover** [Oblong/obi#56]
In a common case for obi, there are 3+ machines to which we need to rsync obi's working directory.  For media-rich applications, this process can be slow.  But it is essential to productivity that we continue to support and improve that use case.

It is almost always the case that the network connection among the target machines is at least as fast, if not much faster, than the connection from laptop or developer workstation to those machines.  In basically every case we've encountered so far, it's Wifi vs. Gigabit ethernet.

Therefore, an rsync strategy in which we rsync assets just to one machine, and then rsync again from that machine to its peers, would pay off, if it could be done.

**Comment by tomjakubowski** [comment]
Doesn't this only optimize in the case that the network is the bottleneck and not the disks the files get written to?

**Comment by sandover** [comment]
Yes.  It only optimizes our common use case.

**Comment by tomjakubowski** [comment]
Are you sure that network is the bottleneck in the common case?

**Comment by sandover** [comment]
We've never encountered a multi-machine environment that wasn't wired -- in fact, they've all been gigabit ethernet, but even just assuming a wire, the wire will be as fast or faster than the connection to the developer machine (which is often wifi).  It would be very unusual for the target machines to be connected via Wifi.  So the among-target network seems safe to assume.

We've never encountered a multi-machine environment where the target machines weren't as fast or faster in terms of CPU than the developer machine.  Our developer machines are, at best, the same generation or older than the target machines.

And I've never encountered a computer where disk I/O wasn't faster than network.

Am I missing something in the thrust of your questions?
