### ISSUE TITLE
Ubuntu install prereq additions

### ISSUE THREAD

**Issue by mattfranklin** [Oblong/obi#60]
I just installed obi on a fresh 16.04 install, and followed the instructions here. In addition to what was listed I had to install git via apt, and pycrypto via pip. May want to update documentation, though I realize many users would already have those installed on a less-than-fresh-install.

**Comment by tomjakubowski** [comment]
Thanks @mattfranklin. From a fresh 16.04 LXD container I needed these dependencies:

```
sudo apt install python-pip libffi-dev libssl-dev
```

I also needed to bump the fabric dependency, see PR #62

**Comment by tomjakubowski** [comment]
README updated.
