### ISSUE TITLE
master/dev sync issues

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#64]
Well, I've been creating and merging PRs, but they've been landing on the master branch and not the dev branch.

Should we set the default branch for this project to "dev" to help avoid this problem?

**Comment by sandover** [comment]
@jshrake before @Gobiner spins up on this project, can you set some policy around master vs. dev?  Maybe document your thoughts in the README?

**Comment by jshrake** [comment]
I make release tarballs off of the HEAD of master (https://github.com/Oblong/homebrew-tools/blob/master/obi.rb#L4)

`brew install obi --HEAD` installs from the HEAD of dev (https://github.com/Oblong/homebrew-tools/blob/master/obi.rb#L6)

All work should land on dev. I announce internally when I push changes to dev, and that ask that dev users update. After a few weeks, if all is well, I'll merge to master and tag a release.

**Comment by sandover** [comment]
added that content to README, closing.
