### ISSUE TITLE
obi go interferes with multi-argument ArgParse-ing

### ISSUE THREAD

**Issue by ebeneliason** [Oblong/obi#65]
obi can conflict with argument parsing when running apps that intend to accept multiple arguments to a single flag via `ArgParse::ArgInts`, `ArgParse::ArgFloats`, or `ArgParse::ArgStrings`. It works fine with the default behavior SEP_NONE, which requires specifying the flag multiple times, but fails for SEP_ARGV, which allows space-separated arguments to be provided up to the next flag.

So, assuming the application does something like:

```
ObTrove <Str> opts;
ArgParse ap (argc, argv);
ap . ArgStrings ("multi", "all your options are belong to me", &opts, ArgParse::SEP_ARGV);
```

Then:
`obi go -- --multi one two three`
…won't do what you want because obi appends (flag-less) screen and feld protein arguments which are interpreted as further args to the `multi` flag. This results in a) use of the system screen/feld proteins, rather than those provided by `obi go`, and b) unexpected values in the `opts` array, which can cause all manner of unwanted behavior within the app.

On the other hand:
`obi go -- --multi one two three --`
…works fine. Perhaps obi should toss in the `--` automatically as a safety precaution?

**Comment by sandover** [comment]
If our programs did not try to slerp .protein files from the end of the arg list, life would be easier.  In the case of solutions, I'm actually ready and willing to change that behavior.

**Comment by sandover** [comment]
> obi appends (flag-less) screen and feld protein arguments

Is that really what it does?

**Comment by tomjakubowski** [comment]
> obi appends (flag-less) screen and feld protein arguments

this was the case for ancient versions of obi, but should no longer be true (and if it is, should be filed as a separate bug)

**Comment by sandover** [comment]
@ebeneliason @jshrake shall we close for now?

**Comment by Gobiner** [comment]
It is still the case that obi can append flagless arguments to your launch command. From an example of `obi go -- --multi one two three`:
```
[localhost] local: OB_SHARE_PATH=share/testsssts:$OB_SHARE_PATH /Users/arice/testsssts/build/testsssts --multi one two three /etc/oblong/screen.protein /etc/oblong/feld.protein
```
This is the launch command used by a new greenhouse project. Most of our projects just happen to have --flagful arguments at the top of their `launch-args` list.

**Comment by Gobiner** [comment]
I am in favor of closing this issue as wontfix. Not only did @ebeneliason note a functioning workaround, but users can modify their `project.yaml` to include `--` as the first element in `launch-args` if their other launch arguments are flagless.

**Comment by sandover** [comment]
I closed this, but then another thought occurred -- should there be better documentation around this?

**Comment by ebeneliason** [comment]
This was baffling to me, and it was not at all obvious that it was a configuration issue rather than an error in my code or a bug in the ArgParse API. What argument is there for putting this burden on the user, rather than ensuring that obi works regardless of what argument parsing structure the user chooses?

**Comment by tomjakubowski** [comment]
@Gobiner ahhh, so obi puts any "extra" arguments passed to `obi go` (i.e. `obi go -- --some-extra args`) *before* the `launch-args` specified in the project.yaml? :goberserk:

I agree with @ebeneliason that this behavior is confusing if you expect those "extra" arguments to come after launch-args. I'd like to know why obi does this.

**Comment by tomjakubowski** [comment]
> I agree with @ebeneliason that this behavior is confusing if you expect those "extra" arguments to come after launch-args. I'd like to know why obi does this.

This is doubly confusing because you might have a room with launch-args specified like this:

```
launch-args: [--enable-missiles]
```

and, for some reason, you might want to run without this option, but just once:

```
obi go -- --disable-missiles
```

expecting the final command line to be something like `./build/nato --enable-missiles --disable-missiles`.  Most argument parsers I've used (not sure about ArgParse), if given conflicting options, use the rightmost option in the argument list. But with obi placing "extra" arguments *before* the launch-args

* * *

FWIW, I don't think the screen and feld protein "have" to come at the end of the command line invocation. With a test Greenhouse application, I ran `./build/foo three-screen.protein three-feld.protein --foo-bar` and the correct screen/feld proteins were selected.  And the documentation for`ArgParse::Leftovers()`, which is often used by non-Greenhouse apps to pass to UrDrome's constructor, says:

```c++
  /**
   * Returns any leftover arguments.  (arguments which didn't start
   * with a dash and didn't get eaten by another option, or any
   * arguments which appeared after "--") Again, this is only valid
   * until the next call to Parse() on this ArgParse object.
   */
  const apstringvec& Leftovers() const;
```

Note that it says nothing about the "leftover" arguments appearing in some particular part of the command line string.

**Comment by Gobiner** [comment]
In an attempt to improve my response above: https://github.com/Oblong/obi/issues/65#issuecomment-279796513

I agree that obi's `extras` should come after the project.yaml's `launch-args`, I think that fits almost all users' expectation, and it's a simple code change.

Given the complexity of obi's "launch target" selection and supporting backwards compatibility, I don't think adding new `--` argument separators is going to be a benefit. The range of obi's potential program invocation, coupled with the range of the invoked program's potential argument parsing, makes me fearful of such a change. My expectation is it would increase the number of unexpected scenarios with unpleasant outcomes like the one @ebeneliason originally reported.

**Comment by sandover** [comment]
Tom, there's code in UrDrome and maybe other places which sniffs the argument list -- g-speak program behavior isn't fully defined by the `ArgParse` class.

**Comment by tomjakubowski** [comment]
Brandon, I've read the code in UrDrome. UrDrome sniffs the trove of arguments *that you pass its constructor*, and in most g-speak applications these are the ArgParse "leftovers". And the sniffed arguments, contrary to popular Solutions mythology, don't have to come at the end; neither the end of the real list of command line arguments nor the end of the list passed to UrDrome.

**Comment by tomjakubowski** [comment]
Sorry, I didn't read the Greenhouse code carefully enough. For workers, it passes `argc` and `argv` directly.

For GUI Greenhouse apps, *Greenhouse* sniffs out arguments matching `.protein` to then pass on to VisiDrome, **but only if they're the last two arguments in the list**. Ugh. This is a total Greenhouse fail, in my opinion.

**Comment by tomjakubowski** [comment]
filed greenhouse issue 59 about that.

**Comment by jshrake** [comment]
Closing in favor of #99, as that seems to be the actual bug. Please re-open if I'm wrong!
