### ISSUE TITLE
need a single record of obi activity on a target machine

### ISSUE THREAD

**Issue by sandover** [Oblong/obi#67]
We sometimes need to answer the question, "What obi go/stop activity has happened on this machine, across all users?" It would be nice to have a way to easily answer that question.  

Possible approach: some high-level logging to /tmp/obi (recording { build, start, stop } activity and including info about user and timestamp)

**Comment by Gobiner** [comment]
From my reading, it appears that shell output redirection can atomically append text to a file (as long as it's under 4KB on linux). Thus, we should be safe to emit `echo "obi info" >> /tmp/obi.log` commands without writes being interrupted or interleaved. It should be pretty simple to add that.

**Comment by Gobiner** [comment]
Here's some kinds of data we could choose to log:
- instigator information
    - user name
    - machine name
    - IP
    - local time
- target machine information
    - user name
    - local time
- obi operation
    - go/stop/rsync/fetch
    - project name
    - launch string

Please suggest your ideas or preferences or concerns.

**Comment by sandover** [comment]
that seems like a reasonable list for v1

**Comment by Gobiner** [comment]
* obi version

**Comment by tomjakubowski** [comment]
@sandover Could you explain here why you think this feature is desirable? 

If an obi-launched program is currently running, it will appear in `ps $(pgrep -f /tmp/)`. If you want to know what programs were running in the past, you can peek at last modified dates for your known users in `/tmp/` and do some guided log drilling. That scenario (knowing what obi programs were running at some distant point in the past) seems pretty niche to me.

**Comment by sandover** [comment]
Commonly heard -- about recent past (in our own staging environment), or about a day or two ago (in the case of client issues reported from the field):

- what app is this? who ran this? 
- was this issue due to having two apps running at once?
- we did have two {app X} instances running at once, how did that happen?
- in the client's fuzzy issue report, how did they run the software in question? was obi in play at the time?

A log seems like a fine way to answer these questions crisply and with timestamps attached (giving us an objective record we can point to when we are being asked to do support). 

(Scrutinizing ps can be OK; rooting around under `/tmp/{set of all users}/{set of all projects}/*.log` is right out.)

**Comment by tomjakubowski** [comment]
"Set of all users" should be very small (probably 1) unless a team is actively using the site as a development environment.

**Comment by jshrake** [comment]
Closing. This is a feature request for a future refactor.
