### ISSUE TITLE
help text and README should make clear that /tmp is the destination

### ISSUE THREAD

**Issue by sandover** [Oblong/obi#68]
We don't clearly tell users the actual rsync destination `/tmp/username/` etc.

**Comment by Gobiner** [comment]
While reading obi source, I discovered that the destination path is configurable per-room. Rooms may have a `project-dir` attribute to override the `/tmp/username/projectname` default.

**Comment by sandover** [comment]
man page should cover that too

**Comment by Gobiner** [comment]
The manpage doesn't include the new text, because the manpage generation doesn't capture that part of the help output (#89). The `project-dir` option will be featured in the example project.yaml (#90).
