### ISSUE TITLE
add short names for obi tasks

### ISSUE THREAD

**Issue by Gobiner** [Oblong/obi#72]
For example, `obi template list` could have a shorter invocation like `obi t ls`.

**Comment by sandover** [comment]
I think @tomjakubowski had some objections to this kind of thing...  

cc @jshrake

**Comment by tomjakubowski** [comment]
I'm fine with having shortcuts as long as they don't clutter `--help` and that the descriptive names  are still the blessed defaults.

**Comment by tomjakubowski** [comment]
It could be too big an ask but [git-style aliases](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases) configurable in both a user config file and a project's project.yaml would be *amazing*.

**Comment by jshrake** [comment]
I think this is an unnecessary LOC increase and widens our bug surface. Given our current resources and lack of tests, I'd like to put this on the back burner.

**Comment by sandover** [comment]
@jshrake is totally right. Kindly move this issue to far in the future, or simply close.
