### ISSUE TITLE
"obi debug" or similar

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#8]
This seems pretty straightforward for local rooms - just prepend `gdb --args` or `lldb --` to the "go" command.

For remote rooms, it's much trickier (especially for multi-host rooms).

**Comment by tomjakubowski** [comment]
One idea is to assume tmux on the remote rooms, create a tmux session and run the "debug" command line (e.g. `gdb --args $GO_CMD`) inside the window, detach from the session and print (for each host) the name of the tmux session.

**Comment by jshrake** [comment]
Closing as I'm happy with the current implementation. Documentation tracking happening in https://github.com/Oblong/obi/issues/17

**Comment by tomjakubowski** [comment]
Not working for me, using a `cef_bless_install_app`'d program:

```
Your current Hardware Enablement Stack (HWE) is no longer supported
since 2014-08-07.  Security updates for critical parts (kernel
GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2.1) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>...
"/tmp/tjakubowski/macroscope/bin/macroscope": not in executable format: File format not recognized
Starting program:  --config=share/macroscope/config.protein --site=share/macroscope/site-table-warehouse.protein --wands-pool=tcp://10.137.124.210/wands --remote-debugging-port=9222 -m --no-sandbox /etc/oblong/screen.protein /etc/oblong/feld.protein
No executable file specified.
Use the "file" or "exec-file" command.
(gdb)
```

Not sure how to get around this… obi can't possibly be aware that the 'real' executable is at another path.
