### ISSUE TITLE
create new obi kill command for sending SIGKILL

### ISSUE THREAD

**Issue by Gobiner** [Oblong/obi#80]
`obi kill` would be just like `obi stop` except sending the processes SIGKILL instead of SIGINT. That would give JC (for example) a reasonable way to kill apps stuck in an infinite loop.

**Comment by tomjakubowski** [comment]
How about instead an command argument to `stop` to choose the signal ? 

To send SIGKILL:
```
% obi stop -s KILL hex
```

To send SIGHUP:

```
% obi stop -s HUP hex
```

**Comment by Gobiner** [comment]
If I `obi go --debug=lldb` on a project, and then run `obi stop` in another terminal, my LLDB instance is not stopped. It's treated as ^C, not a terminate/kill signal.

**Comment by tomjakubowski** [comment]
Also, if `obi stop` sends SIGINT, we ought to change that to be SIGTERM instead. SIGINT is commonly trapped and used for other purposes (for example: many language REPLs). SIGTERM doesn't do something "weird" as commonly as SIGINT in my experience.

**Comment by hightop-oblong** [comment]
@jshrake really didn't like this idea last time i suggested it...

**Comment by jshrake** [comment]
I'm against introducing new commands, especially a command that does the same thing as an existing command. If a user finds herself needing to kill their program with SIGTERM due to infinite loops, they could simply override the existing stop-cmd or use something like ansible/pssh. If we must have something like this, then I'm on board with @tomjakubowski's suggestion.

**Comment by sandover** [comment]
I'd like to point out that nobody seems to really fully understand signals,  except maybe tom and dan. ( this discussion is one evidence of that, but there's lots of other evidence .)  

So....a little bit of tool support seems appropriate ( as long as it's in keeping with the existing design of the tool).  turning developers loose to their own devices, on the other hand,  leaves us all exactly where we are, which is, more or less, blundering around. 

Dev education would also be good. But...in the meantime,  I argue for bringing modest support into obi a la tom's idea. 

It must be really nicely documented and crucially, not assume the user has a  perfect and complete grasp of the semantics of signals already

**Comment by EchoAbstract** [comment]
If we're just redirecting to either the `kill` process or the `kill` syscall then we should just allow an arbitrary signal per @tomjakubowski's suggestion above (as we work on profiling we'll likely need to send signals to enable start and stop of profiling, this may also help with causing gcc to break execution without ctr-c, aka issue #66).

**Comment by johnbcarpenter** [comment]
hey, joining the conversation

**Comment by Gobiner** [comment]
Welcome to the conversation, @johnbcarpenter.

**Comment by tomjakubowski** [comment]
>  If a user finds herself needing to kill their program with SIGTERM due to infinite loops

I think you meant to say SIGKILL here.

@sandover makes the fair point that maybe we shouldn't expect g-speak engineers to understand signals. How about `obi stop` to deliver SIGTERM, `obi stop --force` to deliver SIGKILL, and (for "advanced" users) `obi stop --signal=SIGWINCH` to deliver an arbitrary signal?

also, welcome, @johnbcarpenter

**Comment by Gobiner** [comment]
I like `obi stop --force` for sending SIGKILL.

**Comment by EchoAbstract** [comment]
FWIW, for anyone that doesn't know, the only reason SIGINT and SIGTERM don't stop our current processes in an infinite loop is because we have signal handlers that catch SIGINT and SIGTERM to clean up.  Hence we need SIGKILL to actual kill a program stuck in a loop.

**Comment by jshrake** [comment]
Taking a step back, when a user types `obi stop [room]`, they expect their application to stop. When the application doesn't stop, are they expected to read the documentation to discover `obi stop --force`? What about users who don't explicitly `obi stop`, but expect `obi go` to stop and then start their application. Will they need to `obi go --force`? `obi stop` should just work!

The default stop command needs to do something like: `pkill -SIGTERM -f [regex]; sleep 2; pkill -SIGKILL -f [regex];`. We might even be able to replace the existing default stop command string literal and make no API changes.

**Comment by Gobiner** [comment]
I like `obi stop` sending SIGINT/SIGTERM + SIGKILL, also.

**Comment by tomjakubowski** [comment]
#103 closed this right?

**Comment by Gobiner** [comment]
Indeed it did.
