### ISSUE TITLE
During install: Error: No such file or directory - obi.1

### ISSUE THREAD

**Issue by tdinetta7** [Oblong/obi#93]
Was using steps from the getting started page (https://platform-staging.oblong.com/learning/getting_started.html) and 
received error "Error: No such file or directory - obi.1" 
on step "brew install obi"

**Comment by sandover** [comment]
What did `brew tap Oblong/homebrew-tools` report?

**Comment by EchoAbstract** [comment]
The root issue here is that the `brew` recipe currently thinks the manpage exists, but the official release doesn't have the manpage yet.

To fix this issue:

`brew install obi --HEAD`

Let's keep this open until we release and then close it.

**Comment by sandover** [comment]
@jshrake I move to cut a release immediately.

**Comment by jshrake** [comment]
> @jshrake I move to cut a release immediately.

Done. This issue is resolved.
