### ISSUE TITLE
obi missing bash command completion

### ISSUE THREAD

**Issue by davidnixon** [Oblong/obi#95]
Not really an issue but in case its useful to others ...
[obi-completion.bash.zip](https://github.com/Oblong/obi/files/746482/obi-completion.bash.zip)

sourced in my .bashrc ...
```sh
# custom obi bash completion
if [ -f ~/obi-completion.bash ]; then
    . ~/obi-completion.bash
fi
```

And now `tab` after obi works
obi g`tab` magically-bashily turns into `obi go`

obi go `tab` gives a list of rooms

etc ..

It does not complete everything but still really useful for me.

**Comment by Gobiner** [comment]
This is fixed now! At least in the dev branch.
