### ISSUE TITLE
default remote directory doesn't play nice with multiple working copies

### ISSUE THREAD

**Issue by Gobiner** [Oblong/obi#96]
_Developer Name_, for example, maintains two working copies of a project and would like to be able to quickly `obi go room` from each working copy. Current default is that both working copies will sync to `/tmp/dev_name/project/` and be rebuilt, causing a delay when _DN_ alternates his working copy.

**Comment by Gobiner** [comment]
Having a faster rsync would ameliorate some of this issue, but rebuilding on the destinations would not be improved.

**Comment by tomjakubowski** [comment]
Interesting. A quick workaround would be to change the `project-name` in project.yaml in each worktree.

**Comment by jshrake** [comment]
Good feature request for a future refactor.
